name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.10.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27c95c8527357cf7f8ac04397be3d8ee1fb98a107df8d1a477c73144b68fd71a"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
unsup = "1.1.4"

[options]
datapack-folder = "world/datapacks"
