name = "Sekai Survival Modded"
author = "Lutfilah Dzaky"
version = "1.10.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc792e3defede20e90622770ae45553dd04a35904c27202ccf6bb4fcb0f53083"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
unsup = "1.2.0"

[options]
datapack-folder = "config/paxi/datapacks"
